### ISSUE TITLE
Release for Breeze 0.10

### ISSUE THREAD

**Issue by tbertelsen** [scalanlp/breeze-viz#7]
Breeze 0.10 has been released and many other libraries are using it. If you depend on some of these libraries as well as breeze-viz you will end up with two different versions of brezze.

For example: Users should be able to use this in their `build.sbt`:

```scala
libraryDependencies ++= Seq(
    "org.scalanlp" %% "breeze" % "0.10",
    "org.scalanlp" %% "breeze-viz" % "0.10"
)
```
Currently that will print this error

```
[info] Resolving org.scalanlp#breeze-viz_2.10;0.10 ...
[warn] 	module not found: org.scalanlp#breeze-viz_2.10;0.10
[warn] ==== local: tried
[warn]   /Users/tobber/.ivy2/local/org.scalanlp/breeze-viz_2.10/0.10/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scalanlp/breeze-viz_2.10/0.10/breeze-viz_2.10-0.10.pom
[warn] ==== Sonatype Snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/org/scalanlp/breeze-viz_2.10/0.10/breeze-viz_2.10-0.10.pom
[warn] ==== Sonatype Releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/org/scalanlp/breeze-viz_2.10/0.10/breeze-viz_2.10-0.10.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scalanlp#breeze-viz_2.10;0.10: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by MartinSenne** [comment]
Dear Tobias,

will look into that tomorrow.

Thanks and cheers,

Martin

**Comment by dlwh** [comment]
Hey all,

Just last night I decided to pull breeze-viz back into Breeze proper, so
releases will happen automatically. I'll be cutting a 0.11-M0 release this
week.

**Comment by dlwh** [comment]
there's now a 0.11-M0 release of Breeze-viz.

**Comment by tbertelsen** [comment]
HI David.

Is it possible to do a 0.10 release as well? That is a release that depends on [breeze_2.10 0.10](https://repo1.maven.org/maven2/org/scalanlp/breeze_2.10/0.10/) and [breeze_2.11 0.10](https://repo1.maven.org/maven2/org/scalanlp/breeze_2.11/0.10/) respectively.

Thanks :)

**Comment by dlwh** [comment]
done. should take a bit to propagate to maven central.
